## Experiment 2

## Formation of Loop and Cut-set Matrix

In [49]:
import numpy as np

### Input

In [50]:
n = 4
b = 6
t = n - 1
l = b - t
twigs = np.array([['d', 'e', 'f']])
input_data = np.array([['a', 3, 1], ['b', 1, 2], ['c', 2, 3], ['d', 4, 1], ['e', 2, 4], ['f', 3, 4]])
links = []
# creating links for co-tree
for i in range(b):
    curr_branch = input_data[i][0]
    if curr_branch not in twigs:
        links.append(curr_branch)
links = np.array([links])

In [51]:
# converting branch names to numbers

for i in range(b):
    input_data[i][0] = ord(input_data[i][0]) - ord('a') + 1
input_data = input_data.astype('int')

for i in range(t):
    twigs[0][i]= ord(twigs[0][i]) - ord('a')
twigs = twigs.astype('int')

for i in range(l):
    links[0][i] = ord(links[0][i]) - ord('a')
links = links.astype('int')

In [52]:
input_data

array([[1, 3, 1],
       [2, 1, 2],
       [3, 2, 3],
       [4, 4, 1],
       [5, 2, 4],
       [6, 3, 4]])

In [53]:
links

array([[0, 1, 2]])

In [54]:
twigs

array([[3, 4, 5]])

### Forming Reduced Incidence Matrix

In [55]:
A = np.zeros((n, b), dtype = 'int')

In [56]:
for i in range(b):
    curr_branch = input_data[i][0] - 1
    from_node = input_data[i][1] - 1
    to_node = input_data[i][2] - 1
    
    A[from_node][curr_branch] = 1    #leaving a node => +1
    A[to_node][curr_branch] = -1     #Entering a node => -1

In [57]:
A

array([[-1,  1,  0, -1,  0,  0],
       [ 0, -1,  1,  0,  1,  0],
       [ 1,  0, -1,  0,  0,  1],
       [ 0,  0,  0,  1, -1, -1]])

In [58]:
ref_node = 4

In [59]:
A = np.delete(A, ref_node - 1, axis = 0)

In [60]:
A[:, 0]

array([-1,  0,  1])

In [61]:
Al = np.zeros((n -1, l), dtype = 'int')
Ab = np.zeros((n -1, t), dtype = 'int')

for i in range(l):
    Al[:, i] = A[:, links[0][i]]   # picking those branches which are part of links

for i in range(t):
    Ab[:, i] = A[:, twigs[0][i]]  # picking those branches which are twigs for the tree

In [62]:
Al

array([[-1,  1,  0],
       [ 0, -1,  1],
       [ 1,  0, -1]])

In [63]:
Ab

array([[-1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0,  1]])

## Output

### Creating Cut-Set Matrix

In [64]:
Cb = np.dot(np.linalg.inv(Ab), Al).astype('int')

In [65]:
Ub = np.eye(t, dtype = 'int')

In [66]:
C = np.concatenate((Cb, Ub), axis = 1)

In [67]:
C

array([[ 1, -1,  0,  1,  0,  0],
       [ 0, -1,  1,  0,  1,  0],
       [ 1,  0, -1,  0,  0,  1]])

### Creating Loop Matrix

In [68]:
Ul = np.eye(l, dtype = 'int')

In [69]:
Bl = -1*(Cb.T)

In [70]:
Bl = Bl.astype('int')

In [71]:
Bl

array([[-1,  0, -1],
       [ 1,  1,  0],
       [ 0, -1,  1]])

In [72]:
B = np.concatenate((Ul, Bl) , axis = 1)

In [73]:
B

array([[ 1,  0,  0, -1,  0, -1],
       [ 0,  1,  0,  1,  1,  0],
       [ 0,  0,  1,  0, -1,  1]])