#                                                Exp1- 
#                            Using visual interpretation of graph to form incidence matrix

#### n-> no. of nodes = rows
#### b-> no. of branches = columns

#### Ac -> Complete Incidence Matrix. 
#### A -> Reduced Incidence Matrix

## Import Packages

In [1]:
import numpy as np

## Input Data-

In [2]:
n = 4
b = 6

### (branch, from node, to node)

In [3]:
input = np.array([[1, 1, 2], [2, 4, 1], [3, 4, 2], [4, 3, 4], [5, 1, 3], [6, 3, 2]])

## Output Data-

#### Complete A Matrix

In [4]:
Ac = np.zeros((n, b), dtype = 'int')
Ac

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [5]:
for i in range(b):
    curr_branch = input[i][0] - 1
    from_node = input[i][1] - 1
    to_node = input[i][2] - 1
    
    Ac[from_node][curr_branch] = 1    #leaving a node => +1
    Ac[to_node][curr_branch] = -1     #Entering a node => -1

In [6]:
Ac

array([[ 1, -1,  0,  0,  1,  0],
       [-1,  0, -1,  0,  0, -1],
       [ 0,  0,  0,  1, -1,  1],
       [ 0,  1,  1, -1,  0,  0]])

#### Reduced A Matrix

In [7]:
ref_node = 4

In [8]:
A = np.delete(Ac, (ref_node - 1), axis = 0)
A

array([[ 1, -1,  0,  0,  1,  0],
       [-1,  0, -1,  0,  0, -1],
       [ 0,  0,  0,  1, -1,  1]])

In [9]:
Ac.shape, A.shape

((4, 6), (3, 6))